#!/bin/bash
#
#  This is not for distribution.  I can set up these initial packages
#   for potential authors.   In particular, this script relies on data
#   contained in the appropriate Crubadan data files in /usr/local/share/...
#
#     Guaranteed to only (create and) write in a subdirectory  
#
#  version number can be independent of gramadoir-x.x (and of the 
#  perl versions which are tied to these)

recoder()
{
if [ ${USECRUBADAN} = "y" ]
then
	cat
else
	togail "${TEANGA}" utf8
fi
}
  
if [ $# -ne 4 ]
then
	echo "Usage: addlang xx VERSION [y|n] \"author <email>\""
	echo "\"y\" means use the internal crubadan encoding, \"n\" for utf8"
	exit
fi
TEANGA="${1}"
UPPERTEANGA=`echo "${TEANGA}" | tr "[:lower:]" "[:upper:]"`
VERSION="${2}"
USECRUBADAN="${3}"
AUTHOR="${4}"
CRUBADAN="/usr/local/share/crubadan/${TEANGA}"
THISYEAR=`date +%Y`
if [ ! -e ${CRUBADAN} ]
then
	echo "Need to start crawler first for this language"
	exit
fi
NAME_ENG=`egrep '^name_english ' ${CRUBADAN}/EOLAS | sed 's/^name_english  *//'`
NATIVE=`egrep '^encoding ' ${CRUBADAN}/EOLAS | sed 's/^encoding  *//'`
if [ ${USECRUBADAN} = "n" ]
then
	NATIVE="utf8"
fi
CHARSET=`egrep '^charset ' ${CRUBADAN}/EOLAS | sed 's/^charset  *//'`
BDCHARS=`egrep '^boundary ' ${CRUBADAN}/EOLAS | sed 's/^boundary  *//' | recoder`
INTCHARS=`egrep '^interior ' ${CRUBADAN}/EOLAS | sed 's/^interior  *//' | recoder`
UPPERS=`caps.pl -U ${CHARSET} | recoder`
LOWERS=`caps.pl -L ${CHARSET} | recoder`
DIR="${TEANGA}" # gramadoir-${TEANGA}-${VERSION}"
PERLDIR="${DIR}/Lingua-${UPPERTEANGA}-Gramadoir"
if [ -e "${DIR}" ]
then
	echo "${DIR} already exists..."
	exit
fi
mkdir ${DIR}
mkdir ${PERLDIR}
mkdir ${PERLDIR}/lib
mkdir ${PERLDIR}/lib/Lingua
mkdir ${PERLDIR}/lib/Lingua/${UPPERTEANGA}
mkdir ${PERLDIR}/lib/Lingua/${UPPERTEANGA}/Gramadoir
mkdir ${PERLDIR}/lib/Lingua/${UPPERTEANGA}/Gramadoir/Languages
mkdir ${PERLDIR}/scripts
mkdir ${PERLDIR}/share
mkdir ${PERLDIR}/t


togail "${TEANGA}" good 15 | sed 's/ *\([0-9]*\) \(.*\)/\2 \1/'  | recoder > ${DIR}/3grams-${TEANGA}.txt
cp xx/aonchiall-xx.in ${DIR}/aonchiall-${TEANGA}.in
(echo "ChangeLog Summary"; echo; echo "Version ${VERSION}"; echo "  * Initial Release") > ${DIR}/Changes
cp xx/comhshuite-xx.in ${DIR}/comhshuite-${TEANGA}.in
sed "
s/\^NAME_ENG\^/${NAME_ENG}/
s/\^TEANGA\^/${TEANGA}/
s/\^UPPERTEANGA\^/${UPPERTEANGA}/
s/\^VERSION\^/${VERSION}/
s/\^NATIVE\^/${NATIVE}/
s/\^BDCHARS\^/${BDCHARS}/
s/\^INTCHARS\^/${INTCHARS}/
s/\^UPPERS\^/${UPPERS}/
s/\^LOWERS\^/${LOWERS}/
" xx/configure > ${DIR}/configure
chmod 755 ${DIR}/configure
cp COPYING ${DIR}/COPYING
touch ${DIR}/earraidi-${TEANGA}.bs
touch ${DIR}/eile-${TEANGA}.bs
cp xx/eisceacht-xx.in ${DIR}/eisceacht-${TEANGA}.in
cp xx/giorr-xx ${DIR}/giorr-${TEANGA}
LC_ALL=C sort -u ${CRUBADAN}/GLAN > ${DIR}/lexicon-${TEANGA}.txt
counts.pl ${CRUBADAN}/FREQ ${DIR}/lexicon-${TEANGA}.txt > ${DIR}/freq-${TEANGA}.txt
sed -i 's/.*/& 1/' ${DIR}/lexicon-${TEANGA}.txt
cat ${DIR}/lexicon-${TEANGA}.txt | recoder | ./cabhair.pl -c --encoding=${NATIVE} > ${DIR}/lexicon-${TEANGA}.bs
rm -f ${DIR}/lexicon-${TEANGA}.txt
TEMPFILE=`mktemp`
cat ${DIR}/freq-${TEANGA}.txt | recoder > ${TEMPFILE}
mv -f ${TEMPFILE} ${DIR}/freq-${TEANGA}.txt
sed "/CAPITAL/s/A-Z/${UPPERS}/" xx/macra-xx.meta.pl > ${DIR}/macra-${TEANGA}.meta.pl
# get MANIFEST, MANIFEST.SKIP from gramadoir 
cp xx/morph-xx.txt ${DIR}/morph-${TEANGA}.txt
touch ${DIR}/nocombo-${TEANGA}.txt
echo "1 <U>" > ${DIR}/pos-${TEANGA}.txt
sed "s/@TEANGA@/${TEANGA}/; s/@NAME_ENGLISH@/${NAME_ENG}/" README-xx > ${DIR}/README
cp xx/rialacha-xx.in ${DIR}/rialacha-${TEANGA}.in
cp xx/unigram-xx.pre ${DIR}/unigram-${TEANGA}.pre
cp xx/unigram-xx.txt ${DIR}/unigram-${TEANGA}.txt
sed -i "s/(C) 20.. /(C) ${THISYEAR} /" ${DIR}/*-${TEANGA}.in ${DIR}/macra-${TEANGA}.meta.pl
sed -i "/Copyright.*Kevin P\. Scannell/s/.*/&\n#                    ${AUTHOR}/" ${DIR}/*-${TEANGA}.in ${DIR}/macra-${TEANGA}.meta.pl ${DIR}/morph-${TEANGA}.txt
sed -i "/Copyright.*Kevin P\. Scannell/s/.*/&\n                     ${AUTHOR}/" ${DIR}/README
sed -i "
s/\^NAME_ENG\^/${NAME_ENG}/
s/\^TEANGA\^/${TEANGA}/
" ${DIR}/morph-${TEANGA}.txt
