#!/bin/bash
#  used from gramadoir  "benchmark" makefile target.

# filter that makes everything in thousandths of secs
timefix()
{
sed 's/^[0-9]*\.[0-9][0-9]$/&0/' |
sed 's/^[0-9]*\.[0-9]$/&00/' |
sed 's/^[0-9]*$/&.000/' |
sed 's/^[0-9]*\.$/&000/' | tr -d '.' |
sed 's/^00*\([1-9].*\)$/\1/' |
sed 's/^00*$/0/' | sed 's/[0-9]$//'
}

PROFTXT=`mktemp`
dprofpp -O 100 | sed '/^ 0.00 *-/,$d' > ${PROFTXT}
UNCHECKED=`sed -n '/Gramadoir::unchecked/{s/^ [^ ]*  *[^ ]*  *\([^ ]*\).*/\1/; p}' ${PROFTXT} | timefix`
MEMOIZE=`sed -n '/Memoize::__ANON__/{s/^ [^ ]*  *\([^ ]*\).*/\1/; p}' ${PROFTXT} | timefix`
CTR=`sed -n '/Gramadoir::new/{s/^ [^ ]*  *[^ ]*  *\([^ ]*\).*/\1/; p}' ${PROFTXT} | timefix`
COMHSHUITE=`sed -n '/Gramadoir::comhshuite/{s/^ [^ ]*  *\([^ ]*\).*/\1/; p}' ${PROFTXT} | timefix`
AONCHIALLTOT=`sed -n '/Gramadoir::aonchiall$/{s/^ [^ ]*  *\([^ ]*\).*/\1/; p}' ${PROFTXT} | timefix`
UNIGRAM=`sed -n '/Gramadoir::unigram/{s/^ [^ ]*  *\([^ ]*\).*/\1/; p}' ${PROFTXT} | timefix`
RIALACHA=`sed -n '/Gramadoir::rialacha/{s/^ [^ ]*  *\([^ ]*\).*/\1/; p}' ${PROFTXT} | timefix`
EISC=`sed -n '/Gramadoir::eisceacht/{s/^ [^ ]*  *\([^ ]*\).*/\1/; p}' ${PROFTXT} | timefix`
AONCHIALLDEUX=`sed -n '/Gramadoir::aonchiall_/{s/^ [^ ]*  *[^ ]*  *\([^ ]*\).*/\1/; p}' ${PROFTXT} | timefix`
API=`sed -n '/Gramadoir::grammatical/{s/^ [^ ]*  *\([^ ]*\).*/\1/; p}' ${PROFTXT} | timefix`
LOGANU=`sed -n '/Gramadoir::localize/{s/^ [^ ]*  *[^ ]*  *\([^ ]*\).*/\1/; p}' ${PROFTXT} | timefix`
TOTAL=`sed -n '/^  User+System/{s/^[^=]*= \([0-9]*\.[0-9][0-9][0-9]\).*/\1/; p}' ${PROFTXT} | timefix`
TODAY=`date +"%Y-%m-%d"`
echo -e "${TODAY}     $((${UNCHECKED} - ${MEMOIZE}))\t$((${MEMOIZE}+${CTR}))\t${COMHSHUITE}\t$((${AONCHIALLTOT} - ${AONCHIALLDEUX}))\t${AONCHIALLDEUX}\t${UNIGRAM}\t${RIALACHA}\t${EISC}\t$((${API}+${LOGANU}))\t${TOTAL}"
rm -f ${PROFTXT}
