#!/bin/bash
#
#   eventually this script will go away when I build the 
#   perl module directly from the .in files w/o doing the
#   .pl files as a separate step.
#
#   Or said better, these transformations will be composed/combined
#   with the ones currently in the makefile.
#
#   Two arguments; first is the iso-639 code for the language and 
#   the second is the name of the language in English for use in 
#   the plain text docs.   Should fit into this phrase:
#   "NLP tools for the ${2} language"
if [ $# -ne 3 ]
then
	echo "Usage: buildperl xx name_english [y|n] [native|utf8]"
	echo "   y iff the hash tables should be rebuilt/reinstalled"
	echo "You should be using this via the makefile target \"perl\" or \"perldb\"."
	exit 1
fi
if echo "${1}" | grep '[A-Z]' > /dev/null
then
	echo "The ISO-639 code should be given in lowercase"
	echo "You should be using this via the makefile target \"perl\" or \"perldb\"."
	exit 1
fi
TEANGA="${1}"
UPPERTEANGA=`echo "${TEANGA}" | tr "[:lower:]" "[:upper:]"`
NATIVE=`grep "^${TEANGA} " TEANGACHA | sed "s/^${TEANGA}  *\([^ ]*\).*/\1/"`
TARGET=${NATIVE}
if [ "${4}" = "utf8" ]
then
	TARGET="utf8"
	sed -i '/#.*binmode/s/#//g' Lingua-${UPPERTEANGA}-Gramadoir/Makefile.PL
else
	sed -i '/^[^#]*binmode/s/^/#/' Lingua-${UPPERTEANGA}-Gramadoir/Makefile.PL
fi
CHARSPEC=`grep "^${TEANGA} " TEANGACHA | sed "s/^${TEANGA}  *[^ ]*  *//"`
BDCHARS=`echo "${CHARSPEC}" | sed "s/ .*//" | iconv -f "${NATIVE}" -t "${TARGET}"`
INTCHARS=`echo "${CHARSPEC}" | sed "s/^[^ ]*  *\([^ ]*\) .*/\1/" | iconv -f "${NATIVE}" -t "${TARGET}"`
REST=`echo "${CHARSPEC}" | sed "s/^[^ ]*  *[^ ]*  *//"`
CAPITALS=`echo "${REST}" | sed 's/ .*//'`
LOWERS=`echo "${REST}" | sed 's/^[^ ]*  *//'`

#  perl scripts to be inserted into Gramadoir.pm...
MOIRFEOLAIOCHT=`mktemp`
AONCHIALL=`mktemp`
COMHSHUITE=`mktemp`
EISCEACHT=`mktemp`
GIORR=`mktemp`
RIALACHA=`mktemp`
UNIGRAM=`mktemp`
cat morph-${TEANGA}.txt | sed '/^#/d' | sed '/^$/d' | sed 's/#.*$//' | sed 's#^\([^\t ]*\)[ \t]*\([^\t ]*\)[ \t]*\([^\t ]*\)#\tif ( $current =~ m/\1/ ) {\n\t\t($newcurrent = $current) =~ s/\1/"\2"/e;\n\t\t$ans = $self->tag_recurse($original, $newcurrent, ($level > \3) ? $level : \3);\n\t\treturn $ans if $ans;\n\t}\n#' | sed 's/""""/""/' | sed 's/\\[Ll]\$\([1-9]\)/".mylc($\1)."/g' | iconv -f "${NATIVE}" -t "${TARGET}" > ${MOIRFEOLAIOCHT}
cat aonchiall-${TEANGA}.pl | egrep '^s/' | sed 's/^/\t/' | iconv -f "${NATIVE}" -t "${TARGET}" > ${AONCHIALL}
cat comhshuite-${TEANGA}.pl | egrep '^s/' | sed 's/^/\t/' | iconv -f "${NATIVE}" -t "${TARGET}" > ${COMHSHUITE}
cat eisceacht-${TEANGA}.pl | egrep '^s/' | sed 's/^/\t/' | iconv -f "${NATIVE}" -t "${TARGET}" > ${EISCEACHT}
cat giorr-${TEANGA} | tr -d '\t' | egrep '^s/' | sed 's/^/\t/' | sed 's/\$charset/@BDCHARS@@INTCHARS@/g' | iconv -f "${NATIVE}" -t "${TARGET}" > ${GIORR}
cat rialacha-${TEANGA}.pl | egrep '^s/' | sed 's/^/\t/' | iconv -f "${NATIVE}" -t "${TARGET}" > ${RIALACHA}
cat unigram-${TEANGA}.pl | egrep '^s/' | sed 's/^/\t/' | iconv -f "${NATIVE}" -t "${TARGET}" > ${UNIGRAM}

# ensure these are rebuilt upon "perl Makefile.PL" below
if [ "${3}" = "y" ]
then
	find "Lingua-${UPPERTEANGA}-Gramadoir" -name '*.hash' | xargs rm -f
fi

# Makefile.PL
sed -i "s/@TEANGA@/${UPPERTEANGA}/g" Lingua-${UPPERTEANGA}-Gramadoir/Makefile.PL

# 3grams.bs
egrep '[0-9][0-9]' /usr/local/share/crubadan/${TEANGA}/3GRAMS | sed 's/ *\([0-9]*\) \(.*\)/\2 \1/' | iconv -f "${NATIVE}" -t "${TARGET}" > Lingua-${UPPERTEANGA}-Gramadoir/share/3grams.bs

# pos.txt
LEXICON="Lingua-${UPPERTEANGA}-Gramadoir/share/pos.bs"
rm -f ${LEXICON}
cat pos-${TEANGA}.txt | iconv -f "${NATIVE}" -t "${TARGET}" > ${LEXICON}
chmod 444 ${LEXICON}

# focail.bs
LEXICON="Lingua-${UPPERTEANGA}-Gramadoir/share/focail.bs"
rm -f ${LEXICON}
cat focail-${TEANGA}.bs | sed '1d' | 
if [ "${TARGET}" = "utf8" ]
then
perl -e '
use Encode;
# convert only word lines, not grammatical bytes!
binmode(STDIN);
local $/ = "\cJ";
while (<STDIN>) {
print Encode::encode( "utf8", $_ );
my $next=<STDIN>;
print $next;
}
' 
else
	cat
fi > ${LEXICON}
chmod 444 ${LEXICON}

# eile.bs
LEXICON="Lingua-${UPPERTEANGA}-Gramadoir/share/eile.bs"
rm -f ${LEXICON}
cat eile-${TEANGA}.bs | sed '1d' | iconv -f "${NATIVE}" -t "${TARGET}" > ${LEXICON}
chmod 444 ${LEXICON}

# earraidi.bs
LEXICON="Lingua-${UPPERTEANGA}-Gramadoir/share/earraidi.bs"
rm -f ${LEXICON}
cat earraidi-${TEANGA}.bs | iconv -f "${NATIVE}" -t "${TARGET}" > ${LEXICON}
chmod 444 ${LEXICON}

# Languages for Localization
LANGPREFIX="Lingua-${UPPERTEANGA}-Gramadoir/lib/Lingua/${UPPERTEANGA}/Gramadoir/Languages"
rm -f ${LANGPREFIX}/*.pm
ls Languages-*.pm |
while read x
do
	cp "${x}" ${LANGPREFIX}/`echo "${x}" | sed 's/^Languages-//'`
done
cp -f Languages.pm ${LANGPREFIX}.pm
sed -i "s/@TEANGA@/${UPPERTEANGA}/g" ${LANGPREFIX}.pm ${LANGPREFIX}/*.pm

# Gramadoir.pm target
MODULE="Lingua-${UPPERTEANGA}-Gramadoir/lib/Lingua/${UPPERTEANGA}/Gramadoir.pm"
rm -f "${MODULE}"
cat 'Gramadoir.pm.in' |
sed "
/^# morphology code goes here/r ${MOIRFEOLAIOCHT}
/^# aonchiall code goes here/r ${AONCHIALL}
/^# comhshuite code goes here/r ${COMHSHUITE}
/^# eisceacht code goes here/r ${EISCEACHT}
/^# giorr code goes here/r ${GIORR}
/^# rialacha code goes here/r ${RIALACHA}
/^# unigram code goes here/r ${UNIGRAM}
" | 
sed "s/@TEANGA@/${UPPERTEANGA}/g" |
sed "s/@NAME_ENGLISH@/${2}/g" |
sed "s/@BDCHARS@/${BDCHARS}/g" |
sed "s/@INTCHARS@/${INTCHARS}/g" |
sed "s/@CAPITALS@/${CAPITALS}/g" |
sed "s/@LOWERS@/${LOWERS}/g" |
sed '/^# [a-z]* code goes here/d' > "${MODULE}"
chmod 444 "${MODULE}"

# gram-xx target
SCRIPT="Lingua-${UPPERTEANGA}-Gramadoir/gram-${TEANGA}.pl"
rm -f "${SCRIPT}"
cat gram.pl |
sed "s/@TEANGA@/${UPPERTEANGA}/g" |
sed "s/@NATIVE@/${NATIVE}/g" |
sed "s/@NAME_ENGLISH@/${2}/g" > "${SCRIPT}"
chmod 444 "${SCRIPT}"

# cleanup
rm -f ${AONCHIALL} ${COMHSHUITE} ${EISCEACHT} ${GIORR} ${RIALACHA} ${UNIGRAM} ${MOIRFEOLAIOCHT}

cd "Lingua-${UPPERTEANGA}-Gramadoir"
perl Makefile.PL
make
