#!/bin/bash
LC_ALL="${2}" /usr/bin/gram-ga.pl --html --version --comheadan="${2}"
(date; echo "Teanga=${2}"; echo "${1}"; echo; echo;) >> /home/httpd/gr.log
echo "${1}" "." | LC_ALL="${2}" /usr/bin/gram-ga.pl --html --aspell --iomlan --comheadan="${2}"
