--- Makefile	2020-05-23 10:15:27.258407448 -0500
+++ Makefile.ok	2020-05-23 10:12:45.059579711 -0500
@@ -60,8 +60,16 @@
 
 Makefile : Makefile.in config.status
 	./config.status
+	patch < Makefile.patch
 	chmod 444 Makefile
 
+Makefile.patch : FORCE
+	rm -f Makefile.patch
+	mv -f Makefile Makefile.ok
+	./configure
+	- diff -u Makefile Makefile.ok > Makefile.patch
+	mv -f Makefile.ok Makefile
+
 config.status: configure
 	./config.status --recheck
 
@@ -81,4 +89,87 @@
 semiclean :
 	rm -f y.tab.* $(LEX_OUTPUT_ROOT).* aonchiall.y rialacha.y
 
+###############################################################################
+#                    REMAINDER IS FOR MAINTAINER ONLY                         #
+###############################################################################
+
+webhome = $(HOME)/public_html/$(PACKAGE_NAME)
+
+installweb : FORCE
+	$(INSTALL_DATA) gramadoir.lsm $(webhome)
+	$(INSTALL_DATA) gramadoir.vim $(webhome)
+	$(INSTALL_DATA) gramadoir.el $(webhome)
+	$(INSTALL_DATA) OOo/gramadoir.sxw $(webhome)
+	cp -f */gram-*.dtd ${HOME}/public_html/dtds
+	chmod 444 ${HOME}/public_html/dtds/gram*.dtd
+
+installcgi : FORCE
+	cp -f gr.cgi /home/httpd/cgi-bin
+	chmod 755 /home/httpd/cgi-bin/gr.cgi
+
+sampla.html sampla-en.html: FORCE
+	(cd ga; $(MAKE) triail.html)
+	sed '/gram-ga\.pl triail/r ga/triail.html' samptemplate.html > sampla.html
+	sed '/gram-ga\.pl triail/r ga/triail.html' samptemplate-en.html > sampla-en.html
+
+bugs.html bugs-en.html: FORCE
+	(cd ga; $(MAKE) bugs.html bugs-en.html)
+	sed '/kscanne ag gmail ponc com/r ga/bugs.html' bugstemplate.html > bugs.html
+	sed '/kscanne at gmail dot com/r ga/bugs-en.html' bugstemplate-en.html > bugs-en.html
+
+maintainer-clean :
+	$(MAKE) distclean
+	rm -f ChangeLog configure sampla.html bugs.html
+
+# as of 0.6 assume cvs2cl is run manually before "make dist"
+dist : FORCE
+	$(LN_S) gr ../$(TARBALL)
+	tar cvhf $(TARBALL).tar -C .. $(TARBALL)/ABOUT-NLS
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/aonchiall.meta.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/cabhair.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/ChangeLog
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/comhshuite.meta.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/config.guess
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/config.rpath
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/config.sub
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/configure
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/configure.ac
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/COPYING
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/count.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/gettext.h
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/gin.meta.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/gram2dtd.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/gramadoir.el
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/Gramadoir.pm.in
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/gramadoir.vim
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/gramdev.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/gram.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/install-sh
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/Languages-en_us.pm
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/Languages.pm
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/lexbuild
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/Lingua-XX-Gramadoir.t
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/Makefile.in
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/Makefile.PL.in
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/Makefile-xx.in
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/MANIFEST
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/MANIFEST.SKIP
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/messages.txt
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/po2perl.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/ponc.in.l
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/ponc.in.y
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/README
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/README.perl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/rialacha.meta.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/OOo/groo.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/OOo/gramadoir.sxw
+	cd po && $(MAKE) dist
+	gzip $(TARBALL).tar
+	chmod 444 $(TARBALL).tar.gz
+	rm -f ../$(TARBALL)
+
+manual: FORCE
+	rm -f $(webhome)/manual/*.html
+	jw -f docbook -b html -o $(webhome)/manual manual.sgml
+
 FORCE :
