--- Makefile	2004-09-05 21:29:20.388671152 -0500
+++ Makefile.ok	2004-09-05 21:28:06.648881304 -0500
@@ -69,8 +69,16 @@
 
 Makefile : Makefile.in config.status
 	./config.status
+	patch < Makefile.patch
 	chmod 444 Makefile
 
+Makefile.patch : FORCE
+	rm -f Makefile.patch
+	mv -f Makefile Makefile.ok
+	./configure
+	- diff -u Makefile Makefile.ok > Makefile.patch
+	mv -f Makefile.ok Makefile
+
 config.status: configure
 	./config.status --recheck
 
@@ -90,4 +98,92 @@
 semiclean :
 	rm -f y.tab.* $(LEX_OUTPUT_ROOT).* aonchiall.y eisceacht.y rialacha.y
 
+###############################################################################
+#                    REMAINDER IS FOR MAINTAINER ONLY                         #
+###############################################################################
+
+webhome = $(HOME)/public_html/$(PACKAGE_NAME)
+
+installhtml : sampla.html FORCE
+	$(INSTALL_DATA) cuidiu.html $(webhome)
+	$(INSTALL_DATA) eagar.html $(webhome)
+	$(INSTALL_DATA) foirm.html $(webhome)
+	$(INSTALL_DATA) form.html $(webhome)
+	$(INSTALL_DATA) index.html $(webhome)
+	$(INSTALL_DATA) iompar.html $(webhome)
+	$(INSTALL_DATA) sios.html $(webhome)
+	$(INSTALL_DATA) stair.html $(webhome)
+	$(INSTALL_DATA) sampla.html $(webhome)
+
+installweb : FORCE
+	$(MAKE) installhtml
+	$(INSTALL_DATA) gramadoir.dtd $(webhome)/../dtds
+	$(INSTALL_DATA) gramadoir.lsm $(webhome)
+	$(INSTALL_DATA) gramadoir.vim $(webhome)
+	$(INSTALL_DATA) gramadoir.el $(webhome)
+	$(INSTALL_DATA) OOo/gramadoir.sxw $(webhome)
+
+installcgi : FORCE
+	cp -f gr.cgi /home/httpd/cgi-bin
+	chmod 755 /home/httpd/cgi-bin/gr.cgi
+
+sampla.html : FORCE
+	(cd ga; $(MAKE) triail.html)
+	sed '/gram-ga\.pl triail/r ga/triail.html' samptemplate.html > sampla.html
+
+maintainer-clean :
+	$(MAKE) distclean
+	rm -f ChangeLog configure sampla.html
+
+ChangeLog : FORCE
+	cvs2cl.pl
+
+dist : FORCE
+	$(MAKE) ChangeLog
+	$(LN_S) gr ../$(TARBALL)
+	tar cvhf $(TARBALL).tar -C .. $(TARBALL)/ABOUT-NLS
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/aonchiall.meta.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/cabhair.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/ChangeLog
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/comhshuite.meta.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/config.guess
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/config.rpath
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/config.sub
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/configure
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/configure.ac
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/COPYING
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/count.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/eisceacht.meta.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/gettext.h
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/gin.meta.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/gramadoir.dtd
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/gramadoir.el
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/Gramadoir.pm.in
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/gramadoir.vim
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/gramdev.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/gram.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/install-sh
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/Languages-en_us.pm
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/Languages.pm
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/lexbuild
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/Lingua-XX-Gramadoir.t
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/Makefile.in
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/Makefile.PL.in
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/Makefile-xx.in
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/MANIFEST
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/MANIFEST.SKIP
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/po2perl.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/ponc.in.l
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/ponc.in.y
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/README
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/README.perl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/README-xx
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/rialacha.meta.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/OOo/groo.pl
+	tar rvhf $(TARBALL).tar -C .. $(TARBALL)/OOo/gramadoir.sxw
+	cd po && $(MAKE) dist
+	gzip $(TARBALL).tar
+	chmod 444 $(TARBALL).tar.gz
+	rm -f ../$(TARBALL)
+
 FORCE :
