#!/bin/bash

test_language()
{
export LC_ALL="${1}" 
echo "test help flag"
gr --help
echo "test version flag"
gr --version
echo "test segmentation"
echo "Several.  Sentences.  Here!" | gr --iomlan
echo "test litriu flag"
gr --litriu --iomlan triail.2
echo "test xml flag"
gr --xml --iomlan triail.2
echo "test html flag"
gr --html --iomlan triail.2
echo "test ionchod flag and ability to read from stdin"
cat triail.2 | iconv -f iso88591 -t utf8 | gr --ionchod=utf8
echo "test English"
head -n 42 COPYING | gr --iomlan --teanga=en --xml
echo "test English: ASCII character set"
echo 'This string has embédded non-ASCII characters!' | gr --xml --iomlan --teanga=en
echo "test aspell support"
echo "Militriu." | gr --iomlan --aspell
echo "test brill algorithm"
gr --brill --iomlan triail
echo "test tag frequency counter"
gr --iomlan --minic triail
echo "test ambiguity report"
gr --iomlan --ilchiall triail
echo "test various error messages" >&2
rm -f nonexistentfile
gr nonexistentfile
gr ${HOME}
gr /etc/shadow
gr --fakeoption /dev/null
gr --fakeoption=fakearg /dev/null
gr --teanga /dev/null
gr --xml=fakearg /dev/null
gr --teanga=el /dev/null
gr --teanga=EN --aspell /dev/null
gr --ionchod=fakecode /dev/null
##  add stuff for ponc.in  checks
mv /usr/local/share/gramadoir/focail-ga.bs ./f.bs
gr --litriu triail.2
mv ./f.bs /usr/local/share/gramadoir/focail-ga.bs
mv /usr/local/share/gramadoir/eile-ga.bs ./e.bs
gr --litriu triail.2
mv ./e.bs /usr/local/share/gramadoir/eile-ga.bs
}

do_all()
{
head triail > triail.2
test_language POSIX
test_language de_DE
test_language ga_IE
test_language ga_IE.utf8
test_language ro_RO
test_language nl_NL
rm -f triail.2
}

do_all > stress.out 2> stress.err
