#!/usr/bin/perl
# Macros used in converting *.in files into *.pl scripts
# Copyright (C) 2004 Kevin P. Scannell <scannell@slu.edu>
#
# This is free software; see the file COPYING for copying conditions.  There is
# NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
s/ANYTHING/[^<]+/g;
s/CAPITALLENITED/[BCDFGMPST]h[^<]+/g;
s/CAPITAL/[A-Z¡…Õ”⁄][^<]*/g;
s/CAPVOWEL/[AEIOU¡…Õ”⁄][^<]*/g;
s/CAPVOWELWITHH/h[AEIOU¡…Õ”⁄][^<]*/g;
s/LENITEDFUTURE/[Gg]heo[^<]+/g;
s/ABAIRPAST/[Dd]˙(?:irt|ra[dm]ar|radh)/g;
s/ABAIRPRFU/[Dd](?:eir|Èar)[^<]*/g;
s/FAIGHFC/bhfaigh[^<]+/g;
s/ABSPASTVERB/(?:rinne[^<]*|chonai?c[^<]*|chua(?:igh|[md]ar|thas)|bhÌ(?:o[md]ar|othas)?)/g;
s/ABSNONPASTVERB/(?:n?gh?eo[bf][^<]+|d'Ìosf[^<]+|t·(?:im|imid|thar)?)/g;
# "nÌ bhfaighimid" is dep fut, but "faighimid" is abs pres so leave it out
s/DEPENDENT/(?:rai?bh(?:a[md]ar|thas)?|bhfuil(?:im|imid|tear)?|n?dh?each(?:aigh|a[md]ar|thas)|Ìosf[a·][^<]+|(?:bhf|fh)ac(?:a|a[dm]ar|thas)|(?:bhf|fh)aigh(?:idh|fear|inn|fe·|eadh|imis|idÌs|fÌ)|n?dh?earn[^<]+)/g;
s/JUSTTA/[Tt]·(?:i[dm]|imid|thar)?/g;
s/NONRFORMCONJ/(?:[Gg]o|[Mm]ura|[Ss]ula)/g;
# d· done separately b/c of aonchiall issues
s/NONRFORMPREP/(?:faoi|i|le|Û|trÌ)na/g;
s/RFORMCONJ/(?:[Gg]ur|[Mm]urar|[Ss]ular)/g;
s/RFORMPREP/(?:d·r|(?:faoi|i|le|Û|trÌ)nar)/g;
s/COMPOUND/[^< ]+ [^<]+/g;
s/GENITIVEPREP/(?:[Cc]ois|[Dd]·la|[Ff]earacht|[Tt]impeall|[Tt]rasna)/g;
s/IRREGULARPAST/(?:raibh|dt·inig|dtug|ndearnadh|gcuala|bhfuair)/g;
s/PASTNORFORMLEN/(?:d˙i?r|rai?bh|fuai?r|fhac|dheach|dhearna)[^<]*/g;
s/PASTNORFORM/(?:nd˙i?r|rai?bh|bhfuai?r|bhfac|ndeach|ndearna)[^<]*/g;
s/PASTAFTERNI/(?:bhfuai?r|d˙i?r|rai?bh|fhac|dheach|dhearna)[^<]*/g;
s/FAIGHECLIPSE/[Ff]uai?r[^<]*/g;
s/VOWELNUMERAL/(?:[0-9]?[18]|1?8[0-9][0-9][0-9]*)/g;
s/VOWELORDINAL/(?:80|[0-9]?[18]|1?8[0-9][0-9][0-9]*)˙/g;
s/NIBS/[Nn]Ì(?: ?ba|b)/g;
s/INITIALN/[Nn][^<]+/g;
s/INITIALH/h[^<]+/g;
s/UNLENITEDS/[Ss][lnraeiou·ÈÌÛ˙][^<]+/g;
s/INITIALS/[Ss][lnraeiou·ÈÌÛ˙h][^<]+/g;
s/INITIALVOWELORF/(?:[aeiouAEIOU·ÈÌÛ˙¡…Õ”⁄]|[Ff]h?[aeiou·ÈÌÛ˙])[^<]+/g;
s/INITIALVOWEL/[aeiouAEIOU·ÈÌÛ˙¡…Õ”⁄][^<]*/g;
s/INITIALCONSONANT/[^aeiouAEIOU·ÈÌÛ˙¡…Õ”⁄][^<]+/g;
s/NONVOWELNONF/(?:[^aeiouAEIOU·ÈÌÛ˙¡…Õ”⁄fF]|[Ff]h?[lr])[^<]+/g;
s/UNECLIPSEDDT/(?:[tT]|d[^Tt'])[^<]+/g;
# note this rule doesn't represent all possible eclipses since m/n don't ecl.
s/UNECLIPSEDCONS/(?:[cfptCFPT]|d[^Tt']|g[^Cc]|b[^Pph]|bh[^fF])[^<]+/g;
s/UNECLIPSED/(?:[aeiouAEIOU·ÈÌÛ˙¡…Õ”⁄cfptCFPT]|d[^Tt']|g[^Cc]|b[^Pph]|bh[^fF])[^<]*/g;
s/ECLIPSEDVOWEL/n(?:-[aeiou·ÈÌÛ˙]|[AEIOU¡…Õ”⁄])[^<]*/g;
s/ECLIPSED/(?:n(?:-[aeiou·ÈÌÛ˙]|[AEIOU¡…Õ”⁄])|d[Tt]|g[Cc]|b[Pp]|m[Bb]|n[DdGg]|bh[fF])[^<]*/g;
s/INITIALM/[Mm][^<]+/g;
s/UNLENITABLE/(?:[^BbCcDdFfGgMmPpTt]|[Ss][^lnraeiou·ÈÌÛ˙])[^<]*/g;
s/UNLENITEDBCGMP/[BbCcGgMmPp][^h'][^<]*/g;
s/UNLENITEDBCFGMP/(?:[BbCcFfGgMmPp][^h']|bh[fF])[^<]*/g;
s/UNMUTATEDBCFGP/[BbCcFfGgPp][^hcCpP'][^<]*/g;
# s,m+vowel not *definitely* UNMUTATED since it could be an eclipsis scenario 
s/UNMUTATED/[BbCcDdFfGgPpTt][^hcCpPtT'][^<]*/g;
s/UNLENITEDF/[Ff][aeiou·ÈÌÛ˙][^<]*/g;
s/UNLENITED/(?:[BbCcDdFfGgMmPpTt][^h']|[Ss][lnraeiou·ÈÌÛ˙]|bh[Ff])[^<]*/g;
s/ORDINALADJ/(?:[^<][^<]*[^m]|[0-9]+)˙/g;
s/PREFIXEDT/t(?:[AEIOU¡…Õ”⁄]|-[aeiou·ÈÌÛ˙])[^<]+/g;
# gan/chun/ainneoin disallow "[^ >]+n"
s/FUSEDPOSS/(?:[Dd]·r?|(?:[Ff]aoi|[Ii]|[Ll]e|[Tt]rÌ)n(?:a|·r))/g;
s/FUSEDPREP/(?:[Dd][eo]n|[Ss]an?|[Ff]aoin|[”Û]n)/g;
s/DATIVEPREP/(?:[Aa][rs]|[Dd][eo]|[Ff]aoi|[Gg]an|[Ll]e|[”Û]|[Ii]n?)/g;
s/INITIALTS/t[sS][^<]+/g;
s/INITIALL/[Ll][^<]+/g;
s/INITIALDAPOST/d'[^<]+/g;
s/INITIALBAPOST/b'[^<]+/g;
s/LENITEDBCFGMPS/(?:[CcFfGgMmPpSs]h|[Bb]h[^fF])[^<]+/g;
s/MUTATEDDST/(?:n[Dd]|d[Tt]|[DdSsTt]h)[^<]+/g;
s/LENITEDDFST/[DdFfSsTt]h[^<]+/g;
s/LENITEDDST/[DdSsTt]h[^<]+/g;
s/LENITED/(?:[CcDdFfGgMmPpSsTt]h|[Bb]h[^fF])[^<]+/g;
s/SLENDERFINALCONSONANT/[^<]*[eÈiÌ][^aeiou·ÈÌÛ˙<]+/g;
s/BROADFINALCONSONANT/[^<]*[a·oÛu˙][^aeiou·ÈÌÛ˙<]+/g;
s/FINALVOWEL/[^<]*[^bcdfghjlmnprstvxz<]+/g;
s/FINALA/[^<]*[A¡a·]/g;
s/NOBEEAPOST/(?:[^b]|b[^'])[^<]+/g;
s/NOTVNISHVN/(?:bheith|cheannach|chur|dhÌol|dhul|fhoghlaim|Ìoc|iompar|oscailt|r·|roinnt|scrÌobh|shol·thar|theacht)/g;
s/VNISH/[^<]*(?:a[dm]h|i[nr]t|·il|˙)/g;
s/NOTDO/[^<][^<][^<]+/g;
############################################################################
s/AWITHGSM/(?:<N pl="y"[^>]*>)*(?:<A[^>]*>)*<A pl="n" gnt="y" gnd="m".>(?:<A[^>]*>)*/g;
s/AWITHGSF/(?:<N pl="y"[^>]*>)*(?:<A[^>]*>)*<A pl="n" gnt="y" gnd="f".>(?:<A[^>]*>)*/g;
s/ANYWITHGSF/(?:<N pl="y"[^>]*>)*(?:<[^>]*>)*<A pl="n" gnt="y" gnd="f".>(?:<[^>]*>)*/g;
s/AWITHPL/(?:<N pl="y"[^>]*>)*(?:<A[^>]*>)*<A pl="y" gnt="n".>/g;
s/AWITHCOMMON/(?:<N pl="y"[^>]*>)*<A pl="n" gnt="n".>(?:<A[^>]*>)*/g;
s/ANYWITHCOMMONH/(?:<[^>]*>)*<A pl="n" gnt="n" h="y".>(?:<[^>]*>)*/g;
s/ANYWITHCOMMON/(?:<[^>]*>)*<A pl="n" gnt="n".>(?:<[^>]*>)*/g;
s/ANYNMGPL/(?:<[^>]*>)*<N pl="y" gnt="y" gnd="m"(?: h="y")?.>(?:<[^>]*>)*/g;
s/ANYNFGPL/(?:<[^>]*>)*<N pl="y" gnt="y" gnd="f"(?: h="y")?.>(?:<[^>]*>)*/g;
s/ANYNMG/(?:<[^>]*>)*<N pl="n" gnt="y" gnd="m"(?: h="y")?.>(?:<[^>]*>)*/g;
s/ANYNFG/(?:<[^>]*>)*<N pl="n" gnt="y" gnd="f"(?: h="y")?.>(?:<[^>]*>)*/g;
s/ANYNMC/(?:<[^>]*>)*<N pl="n" gnt="n" gnd="m"(?: h="y")?.>(?:<[^>]*>)*/g;
s/ANYNFC/(?:<[^>]*>)*<N pl="n" gnt="n" gnd="f"(?: h="y")?.>(?:<[^>]*>)*/g;
s/ANYNMPL/(?:<[^>]*>)*<N pl="y" gnt="n" gnd="m"(?: h="y")?.>(?:<[^>]*>)*/g;
s/ANYNFPL/(?:<[^>]*>)*<N pl="y" gnt="n" gnd="f"(?: h="y")?.>(?:<[^>]*>)*/g;
s/ANYCOPULA/(?:<[^>]*>)*<V cop="y".>(?:<[^>]*>)*/g;
s/ANYPASTIMPER/(?:<[^>]*>)*<V p="y" t="ord".><V p="y" t="caite".>(?:<[^>]*>)*/g;
s/ANYIMPER/(?:<[^>]*>)*<V p="y" t="ord".>(?:<[^>]*>)*/g;
s/ANYPASTAUT/(?:<[^>]*>)*<V p="n" t="caite".>(?:<[^>]*>)*/g;
s/ANYPAST/(?:<[^>]*>)*<V p="y" t="caite".>(?:<[^>]*>)*/g;
s/NMWITHHIMPER/<N pl="n" gnt="n" gnd="m" h="y".><V p="y" t="ord".>/g;
s/NFWITHHIMPER/<N pl="n" gnt="n" gnd="f" h="y".><V p="y" t="ord".>/g;
s/NFONEC/<N pl="n" gnt="n" gnd="f".><N pl="y" gnt="y" gnd="f".>/g;
s/ANYNMONEC/(?:<[^>]*>)*<N pl="n" gnt="n" gnd="m"(?: h="y")?.><N pl="y" gnt="y" gnd="m"(?: h="y")?.>(?:<[^>]*>)*/g;
s/ANYNMONE/(?:<[^>]*>)*<N pl="n" gnt="y" gnd="m"(?: h="y")?.><N pl="y" gnt="n" gnd="m"(?: h="y")?.>(?:<[^>]*>)*/g;
s/NMONEADJ/<N pl="n" gnt="n" gnd="m"(?: h="y")?.><N pl="y" gnt="y" gnd="m"(?: h="y")?.><A pl="n" gnt="n".>/g;
s/NMONEC/<N pl="n" gnt="n" gnd="m"(?: h="y")?.><N pl="y" gnt="y" gnd="m"(?: h="y")?.>/g;
s/NMONE/<N pl="n" gnt="y" gnd="m"(?: h="y")?.><N pl="y" gnt="n" gnd="m"(?: h="y")?.>/g;
s/ANDROGYN/<N pl="n" gnt="n" gnd="f".><N pl="n" gnt="y" gnd="m".>/g;
s/STRONGPLM/<N pl="y" gnt="n" gnd="m"(?: h="y")?.><N pl="y" gnt="y" gnd="m"(?: h="y")?.>/g;
s/STRONGPLF/<N pl="y" gnt="n" gnd="f"(?: h="y")?.><N pl="y" gnt="y" gnd="f"(?: h="y")?.>(?:<A pl="n" gnt="y" gnd="f".>)?/g;
s/NMFOUR/<N pl="n" gnt="n" gnd="m".><N pl="n" gnt="y" gnd="m".>(?:<V p="." t="foshuit".>)?/g;
s/NFFOUR/<N pl="n" gnt="n" gnd="f"(?: h="y")?.><N pl="n" gnt="y" gnd="f"(?: h="y")?.>/g;
s/NMADJ/<N pl="n" gnt="n" gnd="m".>(?:<N pl="y" gnt="y" gnd="m".>)?<A pl="n" gnt="n".>(?:<[A-Z][^>]*>)*/g;
s/NFADJ/<N pl="n" gnt="n" gnd="f".><A pl="n" gnt="n".>(?:<[A-Z][^>]*>)*/g;
s/NOUNADJH/(?:<N[^>]*>)+<A pl="n" gnt="n" h="y".>(?:<[AV][^>]*>)*/g;
s/NOUNADJ/(?:<N[^>]*>)+<A pl="n" gnt="n".>(?:<[AV][^>]*>)*/g;
s/NMVERB/<N pl="n" gnt="n" gnd="m".>(?:<V p="y"[^>]*>)+/g;
s/NFVERB/<N pl="n" gnt="n" gnd="f".>(?:<V p="y"[^>]*>)+/g;
s/NMSUBJ/<N pl="n" gnt="n" gnd="m".><V p="." t="foshuit".>/g;
s/NPLMSUBJ/<N pl="y" gnt="n" gnd="m".><V p="." t="foshuit".>/g;
s/NPLFSUBJ/<N pl="y" gnt="n" gnd="f".><V p="." t="foshuit".>/g;
s/NPLF/<N pl="y" gnt="n".><N pl="y" gnt="n" gnd="f".>/g;
s/PLADJSUBJ/<A pl="y" gnt="n".><V p="." t="foshuit".>/g;
s/PRESSUBJ/<V p="y" t="l·ith".><V p="y" t="foshuit".>/g;
s/NFGSUBJ/<N pl="n" gnt="y" gnd="f".><V p="." t="foshuit".>/g;
s/GENADJ/<N pl="n" gnt="y" gnd=".".><A pl="n" gnt="n".>(?:<A [^>]*>)*/g;
s/PROPER/<Y.>(?:<[^>]*>)+/g;
s/MASCPL/<N pl="y" gnt="n".><N pl="y" gnt="n" gnd="m".>/g;
s/ADJADV/<R.><A pl="n" gnt="n".>/g;
s/PREPCONJ/<S.><C.>/g;
s/PREPPOSS/<S.><D.>/g;
s/PREPADV/<S.><R.>(?:<A pl="n" gnt="n".>)?/g;
s/PREPPRONM/<S.><O.>/g;
s/TEMPORAL/<R.><N pl="n" gnt="n".>/g;
s/SEOSIN/<P.><A pl="n" gnt="n".>(?:<A pl="n" gnt="y" gnd="m".>)?/g;
s/BHIODHLIKE/<V p="y" t="ord".><V p="y" t="gn·th".>/g;
# s/BHIDISLIKE/<V pl="y" p="[13]˙" t="ord".><V pl="y" p="[13]˙" t="gn·th".>/g;
s/PAUTGNATH/<V p="n" t="caite".><V p="y" t="ord".><V p="y" t="gn·th".>/g;
s/ADHWORD/<N pl="n" gnt="n" gnd="m".><V p="n" t="caite".><V p="y" t="ord".>(?:<V p="y" t="gn·th".>)?/g;
s/GENERICPAST/<V p="y" t="ord".><V p="y" t="caite".>/g;
s/GENERICAUT/(?:<V p="n" t="ord".>)?<V p="n" t="l·ith".>(?:<V p="n" t="foshuit".>)?/g;
s/GENERICPAUT/<V p="n" t="caite".><V p="y" t="ord".>/g;
s/GENERICFIRST/<V p="y" t="ord".><V p="y" t="l·ith".>/g;
s/NUMERICAL/<N pl="n" gnt="n" gnd="m".><N pl="n" gnt="y" gnd="m".><A pl="n" gnt="n".>/g;
s/COPULAPART/<U.><C.><Q.><V cop="y".>/g;
############################################################################
s/\*S\[/*pl="n"[/g;
s/\*P\[/*pl="y"[/g;
s/\*C\[/*gnt="n"[/g;
s/\*G\[/*gnt="y"[/g;
s/\*D\[/*gnt="d"[/g;
s/\*CP\[/*pl="y" gnt="n"[/g;
s/\*GP\[/*pl="y" gnt="y"[/g;
s/\*CS\[/*pl="n" gnt="n"[/g;
s/\*GS\[/*pl="n" gnt="y"[/g;
s/\*FCS\[/*pl="n" gnt="n" gnd="f"[/g;
s/\*FCP\[/*pl="y" gnt="n" gnd="f"[/g;
s/\*FGS\[/*pl="n" gnt="y" gnd="f"[/g;
s/\*FGP\[/*pl="y" gnt="y" gnd="f"[/g;
s/\*MCS\[/*pl="n" gnt="n" gnd="m"[/g;
s/\*MCP\[/*pl="y" gnt="n" gnd="m"[/g;
s/\*MGS\[/*pl="n" gnt="y" gnd="m"[/g;
s/\*MGP\[/*pl="y" gnt="y" gnd="m"[/g;
s/\*NOPAUT\[/*(?: p=.y|t=..[^a])[/g;
s/\*DEE\[/*t="(?:caite|gn·th|coinn)"[/g;
s/\*WITHH\[/*h="y"[/g;
s/\*IMP\[/*t="ord"[/g;
s/\*NOLEN\[/*t="[flo][^o][/g;
s/\*PAUT\[/*p="n" t="caite"[/g;
s/\*PAST\[/*t="caite"[/g;
s/\*SUBJ\[/*t="foshuit"[/g;
s/\*NOTPASTSUBJ\[/*t=".[^a][^s][/g;
s/\*NOTPAST\[/*t=".[^a][/g;
s/\*NOTCOP\[/* p="."[/g;
s/\*COP\[/*cop="y"[/g;
