--- Makefile	2020-05-22 11:42:10.665296672 -0500
+++ Makefile.ok	2020-05-22 11:41:34.181567994 -0500
@@ -10,7 +10,7 @@
 
 # general configuration
 ECHO = echo
-EGREP = /bin/grep -E
+EGREP = /bin/grep -E -a
 LN_S = ln -s
 PERL = /usr/bin/perl
 
@@ -74,6 +74,15 @@
 
 Makefile : $(GRAMDIR)/Makefile-xx.in configure
 	./configure
+	patch < Makefile.patch
+	chmod 444 Makefile
+
+Makefile.patch : FORCE
+	rm -f Makefile.patch
+	mv -f Makefile Makefile.ok
+	./configure
+	- diff -u Makefile Makefile.ok > Makefile.patch
+	mv -f Makefile.ok Makefile
 
 test : perl
 	(cd $(PERLD); make test)
@@ -184,6 +193,12 @@
 triail : rialacha-$(TEANGA).in
 	sed -n '/^#\./{s/^#\. //; p;}' rialacha-$(TEANGA).in > triail
 
+triailcheck : FORCE
+	cat triail.xml | LC_ALL=C sed 's/^<error fromy=.*" msg="/<E m="/' > t1.xml
+	$(PERL) -I $(PERLD)/lib $(PERLD)/scripts/$(SCRIPTNAME) --api --iomlan --aspell --comheadan=ga triail | LC_ALL=C sed 's/^<error fromy=.*" msg="/<E m="/' > t2.xml
+	vimdiff t1.xml t2.xml
+	rm -f t1.xml t2.xml
+
 triail.xml-update : FORCE
 	$(MAKE) triail
 	$(MAKE) perl
@@ -213,7 +228,7 @@
 	while read x; \
 	do \
 		sed -n '1,/^"Content-Transfer-Encoding/{/^[^#]/s/^/#/; p;}' $(GRAMDIR)/po/$${x}.po > pometa.txt; \
-		LC_ALL="C" $(PERL) $(GRAMDIR)/po2perl.pl $(GRAMDIR)/po/$${x}.po "$${x}" | iconv -f `$(EGREP) '^"Content-Type:' $(GRAMDIR)/po/$${x}.po | sed 's/^.*charset *= *\([^ ]*\)\\\n.*/\1/'`  -t utf-8 | sed "/^package/r pometa.txt" | sed "s/@TEANGA@/$(UPPERTEANGA)/g" > $(PERLLIB)/Languages/$${x}.pm; \
+		LC_ALL="C" $(PERL) $(GRAMDIR)/po2perl.pl $(GRAMDIR)/po/$${x}.po "$${x}" | sed "/^package/r pometa.txt" | iconv -f `$(EGREP) '^"Content-Type:' $(GRAMDIR)/po/$${x}.po | sed 's/^.*charset *= *\([^ ]*\)\\\n.*/\1/'`  -t utf-8 | sed "s/@TEANGA@/$(UPPERTEANGA)/g" > $(PERLLIB)/Languages/$${x}.pm; \
 		rm -f pometa.txt; \
 	done
 	touch locale_ok
@@ -271,6 +286,7 @@
 	$(MAKE) rebuildlex
 	rm -f Makefile $(PERLDOK) lexicon-$(TEANGA).txt
 	rm -fR $(PERLD)
+	rm -fR gramadoir
 
 clean :
 	if [ -e $(PERLD)/Makefile ]; then (cd $(PERLD);  make distclean); fi
@@ -317,9 +333,9 @@
 replcheck : FORCE
 	@$(MAKE) perl
 	@echo "earraidi-$(TEANGA).bs..."
-	@sed 's/^[^ ]* //; s/$$/\./' earraidi-$(TEANGA).bs | $(PERL) -I $(PERLD)/lib $(PERLD)/scripts/$(SCRIPTNAME) --litriu --iomlan
+	@LC_ALL=C sed 's/^[^ ]* //; s/$$/\./' earraidi-$(TEANGA).bs | $(PERL) -I $(PERLD)/lib $(PERLD)/scripts/$(SCRIPTNAME) --litriu --iomlan
 	@echo "eile-$(TEANGA).bs..."
-	@sed 's/^[^ ]* //; s/$$/\./' eile-$(TEANGA).bs | $(PERL) -I $(PERLD)/lib $(PERLD)/scripts/$(SCRIPTNAME) --litriu --iomlan
+	@LC_ALL=C sed 's/^[^ ]* //; s/$$/\./' eile-$(TEANGA).bs | $(PERL) -I $(PERLD)/lib $(PERLD)/scripts/$(SCRIPTNAME) --litriu --iomlan
 
 
 counts : FORCE
@@ -333,4 +349,109 @@
 zipped : perl
 	(cd $(PERLD); make zipdist)
 
+benchmark : FORCE
+	$(MAKE) perl
+	benchcorp | $(PERL) -I $(PERLD)/lib -d:DProf $(PERLD)/scripts/$(SCRIPTNAME) --ionchod=utf8 --iomlan --dath=none --comheadan=ga > /dev/null
+	bash bmtabla >> ../../eile/benchmarks
+	vi ../../eile/benchmarks
+	rm -f tmon.out
+
+unigram-cand.txt : $(DEVSCRIPTNAME)
+	$(MAKE) perl
+	benchcorp | iconv -f utf8 -t iso-8859-1 | $(PERL) -I $(PERLD)/lib $(DEVSCRIPTNAME) --minic | iconv -f utf8 -t iso-8859-1 > $@
+
+Changes : ../stair.html
+	vilistextum --charset=utf-8 --output-utf-8 $(GRAMDIR)/stair.html - | sed -n '/^ChangeLog/,/----/p' | $(EGREP) -v -- '---' > $@
+
+# use installed version for this
+triail.html : triail
+	/usr/local/bin/gram-ga.pl --iomlan --html --aspell triail > $@
+
+# for cruinneog.com Ceart site
+sampler.html : triail
+	cat triail | egrep -v '\(OK\)' | /usr/local/bin/gram-ga.pl --iomlan --html --aspell > $@
+
+ISPELLDIR = ${HOME}/gaeilge/ispell
+
+# use "groom" instead of this directly (since it requires ispell personal, etc.)
+lexfromdb : FORCE
+	Gin 12
+	sed -i '$$s/$$/\n/' FOCAIL
+	(((cat $(ISPELLDIR)/ispell-gaeilge/personal $(ISPELLDIR)/ispell-gaeilge/uimhreacha; cat $(ISPELLDIR)/ispell-gaeilge/apost | sed 's/ .*//') | bash tolatin1.sh; cat ${HOME}/.ispell_gaeilge | LC_ALL=POSIX ispell -dgaeilge -e3 | tr " " "\n" | $(EGREP) -v '\/' | LC_ALL=POSIX aspell -dga -p${HOME}/.aspell.blank.pws list) | sed 's/$$/& 44/'; cat FOCAIL; cat $(ISPELLDIR)/ispell-gaeilge/dinneenok.txt | sed 's/$$/& 127/' | iconv -f utf8 -t iso-8859-1) | $(PERL) -p posmap.pl | LC_ALL=POSIX sort -u -k1,1 -k2,2n | sed '/^OK /d' > lexicon-ga.txt
+	$(MAKE) rebuildlex
+	rm -f FOCAIL
+
+# for convenience (from groom); but also ensures built in correct order
+gafromdb : FORCE
+	$(MAKE) lexfromdb
+	$(MAKE) eilefromdb
+	$(MAKE) earrfromdb
+
+ATH = ${ISPELLDIR}/ispell-gaeilge/athfhocail
+
+# use "groom" instead of this directly
+eilefromdb : FORCE
+	sed 's/ [0-9]*//' lexicon-ga.txt | iconv -f iso-8859-1 -t utf8 > ./tempfocail
+	sed 's/ .*//' $(ATH) | keepif -n ./tempfocail | LC_ALL=C sort -u | LC_ALL=C join $(ATH) - | LC_ALL=C sort -k1,1 | $(EGREP) '^' | bash tolatin1.sh > ./eile-ga.bs
+	rm -f tempfocail
+
+EARR = ${ISPELLDIR}/ispell-gaeilge/gaelu ${ISPELLDIR}/ispell-gaeilge/earraidi
+
+# use "groom" instead of this directly
+earrfromdb : FORCE
+	sed 's/ [0-9]*//' lexicon-ga.txt eile-ga.bs | iconv -f iso-8859-1 -t utf8 > ./tempfocail
+	LC_ALL=C sort -k1,1 $(EARR) > ./tempsrc
+	sed 's/ .*//' ./tempsrc | keepif -n ./tempfocail | LC_ALL=C sort -u | LC_ALL=C join ./tempsrc - | LC_ALL=C sort -k1,1 | $(EGREP) . | bash tolatin1.sh > ./earraidi-ga.bs
+	rm -f tempfocail tempsrc
+
+lexicon-$(TEANGA).xml : lexicon-$(TEANGA).txt
+	cat lexicon-$(TEANGA).txt | sed 's/ .*//' | LC_ALL=C sort -u | alltags > $@
+
+BIGDIR = ${HOME}/gaeilge/gramadoir/tastail
+
+big.xml-update : FORCE
+	$(MAKE) perl
+	rm -f $(BIGDIR)/big.xml $(BIGDIR)/bigerr.xml
+	if [ -e $(BIGDIR)/big.new.xml ]; \
+	then \
+		mv $(BIGDIR)/big.new.xml $(BIGDIR)/big.xml; \
+	else \
+		benchcorp | $(PERL) -I $(PERLD)/lib $(PERLD)/scripts/$(SCRIPTNAME) --xml --iomlan --ionchod=utf8 --comheadan=ga | sed 's/<E/\n<E/g; s/<\/E>/&\n/g' | sed '/^<E/!{s/ </\n</g}' | $(EGREP) '.' > $(BIGDIR)/big.xml; \
+	fi
+	if [ -e $(BIGDIR)/bigerr.new.xml ]; \
+	then \
+		mv $(BIGDIR)/bigerr.new.xml $(BIGDIR)/bigerr.xml; \
+	else \
+		$(EGREP) '^<E' $(BIGDIR)/big.xml | LC_ALL=C sort > $(BIGDIR)/bigerr.xml; \
+	fi
+
+bigtest : FORCE
+	@$(MAKE) perl
+	@benchcorp | $(PERL) -I $(PERLD)/lib $(PERLD)/scripts/$(SCRIPTNAME) --xml --iomlan --ionchod=utf8 --comheadan=ga | sed 's/<E/\n<E/g; s/<\/E>/&\n/g' | sed '/^<E/!{s/ </\n</g}' | $(EGREP) '.' | tee $(BIGDIR)/big.new.xml | $(EGREP) '^<E' | LC_ALL=C sort > $(BIGDIR)/bigerr.new.xml
+	@if diff -u $(BIGDIR)/big.xml $(BIGDIR)/big.new.xml > $(BIGDIR)/diff1.txt; then echo "XML unchanged."; rm -f $(BIGDIR)/big.new.xml $(BIGDIR)/diff1.txt; else echo "Differences in XML."; fi
+	@if diff -u $(BIGDIR)/bigerr.xml $(BIGDIR)/bigerr.new.xml > $(BIGDIR)/diff2.txt; then echo "Errors unchanged."; rm -f $(BIGDIR)/bigerr.new.xml $(BIGDIR)/diff2.txt; else echo "Differences in errors."; fi
+
+bugs.html : bugs.txt
+	cat bugs.txt | LC_ALL=C sed '/^[^#]/s/\*\([^\*]*\)\*/<b class=gramadoir>\1<\/b>/g; s/^[^#].*/<i>&<\/i><br>/; s/^# *HEADING: *\(.*\)/<hr><h2>\1<\/h2><p>/; s/^# *BUG.*/<\/p><p>/; s/^# \(.*\)/\1<br>/;' > $@
+
+bugs-en.html : bugs-en.txt
+	cat bugs-en.txt | LC_ALL=C sed '/^[^#]/s/\*\([^\*]*\)\*/<b class=gramadoir>\1<\/b>/g; s/^[^#].*/<i>&<\/i><br>/; s/^# *HEADING: *\(.*\)/<hr><h2>\1<\/h2><p>/; s/^# *BUG.*/<\/p><p>/; s/^# \(.*\)/\1<br>/;' > $@
+
+testdtd : FORCE
+	$(MAKE) gram-$(TEANGA).dtd
+	cp -f gram-$(TEANGA).dtd ${HOME}/public_html/dtds
+	/usr/bin/gram-ga.pl --iomlan --aschod=utf-8 --xml --aspell triail > temp.xml
+	xmllint --dtdvalid http://borel.slu.edu/dtds/gram-$(TEANGA).dtd temp.xml
+
+gram-ga.exe : FORCE
+	rm -fR gramadoir
+	rm -f gramadoir.zip
+	mkdir gramadoir
+	cp -Rf $(PERLD)/lib/Lingua gramadoir
+	rm -fR gramadoir/Lingua/GA/Gramadoir/Languages*
+	rm -f gramadoir/Lingua/GA/Gramadoir.pm
+#	(cd gramadoir; pp -o gram-ga.exe -l /lib/libc.so.6 -l /lib/libpthread.so.0 /usr/bin/gram-ga.pl)
+	(cd gramadoir; pp -o gram-ga.exe -x ../$(PERLD)/scripts/gram-ga.pl)
+	zip -r gramadoir.zip gramadoir
+
 FORCE :
